### ISSUE TITLE
the  code is not complete

### ISSUE THREAD

**Issue by boyxiaolong** [hubo1016/vlcp-ssh#1]
some modules are missed. hubo, could you add it?

**Comment by hubo1016** [comment]
What happened exactly? This project depends on another project vlcp(https://github.com/hubo1016/vlcp), it is a wrapper of paramiko

**Comment by hubo1016** [comment]
It is also registered in PyPI, so you may install the library with pip:
pip install vlcpssh
this will install vlcp, paramiko (and paramiko's dependencies), and vlcpssh

This project is really only a helper to integrade paramiko into vlcp (an async-io framework targeting web and SDN), it is not so helpful if you are not using vlcp.

**Comment by boyxiaolong** [comment]
oh, I'm into paramiko recently and run into valcp-ssh via twitter.
now I know it's depend on  vlcp project.
thanks for your reply.
